exclude:
  - aws-ec2-no-public-ingress-sgr
  - aws-ec2-no-public-egress-sgr
  - aws-elb-alb-not-public
  - aws-ec2-no-public-ip-subnet
  - aws-s3-encryption-customer-key
  - aws-iam-no-policy-wildcards
  - aws-cloudtrail-enable-at-rest-encryption
  - aws-cloudtrail-ensure-cloudwatch-integration
  - aws-s3-enable-bucket-logging
  - aws-cloudtrail-require-bucket-access-logging
  - aws-ec2-require-vpc-flow-logs-for-all-vpcs